version: '2'

services:
  orders_web:
    build: ./orders
    command: bash -c "cd orders && gunicorn api.wsgi --bind 0.0.0.0:80 --reload"
    volumes:
      - .:/code
    ports:
      - 80:80
    restart: always

